### ISSUE TITLE
Connection between form factor and raw scattering data?

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/NMRLipids_V-Review#1]
Which is the experimental quantity that the scattering machinery exactly puts out?
How is the form factor is determined from the experimental observables?
Which assumptions are needed here?

There is already some discussion about this in the blog by Peter Heftberger and Georg Pabst, but any kind of information from full explanation with citations to the hints of relevant literature are helpful here.

**Comment by GeorgPabst** [comment]
Two things to consider:
(i) for unilamellar vesicles you can derive the form factor directly from the scattering data as the intensity \propto |F(q)|^2/q^2. So you basically take the square root of the intensity and multiply with the scattering vector (see work by Norbert Kucerka). In general X-ray data has a higher resolution than neutron data, as it goes to higher q.
(ii) for multilamellar vesicles the intensity is a convolute of the form factor and the structure (lattice) factor. So in order to determine the form factor one needs to know the structure factor. It is convenient to fit both, structure factor and form factor. The of course you need models for both. For the structure factor we mostly use the Caille theory, which describes the effect of bending fluctuations. For the form factor different real space models of bilayer structure (electron density/neutron scattering length density) give similar form factors. That is modeling in real space is not very crucial to reciprocal space, i.e. if the fit is ok form factors will be also ok. Often we combine X-rays and neutron get high structural resolution in real space.

**Comment by ohsOllila** [comment]
Thanks. This was extremely useful explanation for me. 

So based on this and the literature we say that:
The form factor from unilamellar vesicles is practically raw data. The form factor from multilamellar vesicles is not raw, in principle, since it depends on the form factor model, in principle. However, in practise it does not depend on that so it is very robust. 
Please, correct if this is not true.

Further, studies where form factors from different sources are overlapped in the q-regions where this was possible, give a good agreement [Curvature Effect on the Structure of Phospholipid Bilayers, Kucerka et al. Langmuir, 2007, 23 (3), pp 1292–1299 http://dx.doi.org/10.1021/la062455t].
From these studies it has been concluded that form factors are the same for unilamellar and multilamellar systems. Is this fully agreed in the field or has this been challenged? I presume that this would also indicate that the form factor fit is reasonable?

**Comment by GeorgPabst** [comment]
ad 1) Yes...form factors are quite robust. It has been discussed before (Michael Wiener) that different models (differing in detail) for the electron density profile yield similar/same form factors. This is actually one of the problems we have as we are more interested in the real space structure.

ad 2) ULV and MLV form factors should be identical, given that the structure is the same. ULVs is one layer and MLVs is basically repeating this one layer in a (liquid) crystalline lattice.

**Comment by ohsOllila** [comment]
I have now written the first draft of the scattering part. Comments from this (and other perspectives) would be highly welcomed.

**Comment by ohsOllila** [comment]
I have now the following important question: 
It is now written in the manuscript that "For multibilayers $F(q)$ is obtained by modeling the SLD (see e.g.~\cite{Heftberger.2014}).". As far as I understand, in this work a model is used for SLD with a number of contraints and this model is fitted to experimental data to get SLD. And then the idea is that the experimental form factor would be the fourier transform of this. If this is correct, the form factor extracted like this is not directly measured quantity, instead it depends on the model and constraints used, at least in principle. Is this true?

**Comment by ohsOllila** [comment]
Follow up: I did now take a another look to some papers with this in mind and it seems to me now that the form factor has been extracted from oriented bilayers by using the theory for structure factor, e.g. Kucerka et al. Biophys. J. 95,2792 (2008), Biophys. J. 88,2626 (2005).

In this case a model for SLD is not used, only a model for structure factor.

So based on this, it seems to me that:
From unilamellar vesicles the FF can be measured directly from intensity.
From oriented multilamellar vesicles the FF has been extracted by using a model for the structure factor.
From non-oriented multilamellar systems the FF has been extracted by using model for the structure factor and for the SLD.

Is this true?

**Comment by GeorgPabst** [comment]
No this is not quite true... A bit difficult to explain in short. I will try. We model the full intensity of MLV, that is S(q) and F(q). Parameters for both contributions are independent. The FT of the SLD gives the form factor as we write in one of the equations. So one could think that different models for the SLD (e.g. slaps, Gaussians, hybrids of both etc.) yield different F(q). It turn out, however, that F(q) is rather insensitive to the choice of SLD model GIVEN that the SLD captures the main SLD features such as e.g. high electron densities in the head and low densities at the chain terminus. In other words: a lipid bilayer can be equally well presented in reciprocal space by many different real-space models (for a discussion see e.g. M.C. Wiener and S.H. White, Biophys. J. 59, 162 (1991) [maybe we should put this reference].
Thus (and this is the catch) as long as we are able to fit MLV data well (i.e. peaks and diffuse scattering with small residuals; peaks are dominated by S(q) and their modulation and diffuse scattering by F(q)) the form factor is solid (no matter what SLD model you chose).

**Comment by GeorgPabst** [comment]
Regarding the follow up: YES.
Side note: The issue for oriented samples is that you need to have a good description of the structure factor. Because you will just divide the intensity by that.

**Comment by ohsOllila** [comment]
Ok. I think I understand what you mean. I will now modify the text accordingly. 

I think that more direct way to compare simulations and experiments would be to take FF from simulations and then use models for structure factor and compare the intensities. Or take the FF from simulations and fit intensity to experiment to get the structure factor. I have not seen anyone doing this, though. 

I also think that the feasibility of large enough simulations to calculate the full scattering intensity may not be that far.

**Comment by GeorgPabst** [comment]
We have done that, but not did not publish. Really makes no difference.

**Comment by ohsOllila** [comment]
Updated version added: https://github.com/NMRLipids/NMRLipids_V-Review/commit/1d7e74d807cfc3ebe861e2a070c9573a9490a452

I will continue tomorrow.

**Comment by ohsOllila** [comment]
This is now discussed in the [publication](http://dx.doi.org/10.1016/j.bbamem.2016.01.019).
