### ISSUE TITLE
How accurate are the experimental form factors?

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/NMRLipids_V-Review#2]
Has this been discussed in the literature already? 

If not, I guess that it would be useful to plot independetly measured form factors into the same plot.

Any kind of information from full exaplanation with citations to the hints of relevant literature are helpful here.

**Comment by GeorgPabst** [comment]
Form factors are quite accurate given that experimental care has been taken. A delicate issue can be subtraction of background (from water and capillary). Plotting form factors from different labs could be interesting...just be careful about potentially different conditions (hydration level, temperature, composition of the aqueous phase)...

**Comment by ohsOllila** [comment]
Indeed, plotting independently measured Form Factors would very convincing. If someone knows two independent data sets measured with same conditions, please let us know (or if someone has even plotted these already).

**Comment by GeorgPabst** [comment]
I will check...but for e.g. POPC we should be able to get data from Norbert Kucerka and we can overlay it then with our MLV data.

**Comment by heftber** [comment]
If I remember correctly we also measured POPC at different Synchrotrons (Triest, Hamburg and Lund?) and as MLVs and OLVs. I think we have already analyzed all the data and therefore FFs should already be computed (see Linda?). I also like this idea of taking FFs from different labs to estimate in a first approximation uncertainties.

**Comment by ohsOllila** [comment]
These are now in Fig. 11 in the [publication](http://dx.doi.org/10.1016/j.bbamem.2016.01.019).
