### ISSUE TITLE
How to calculate the form factor from simulations?

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/NMRLipids_V-Review#3]
As far as I have understood, the form factor is simply a Fourier transform of electron density. I have some quick and dirty scripts to calculate those in the NMRLipids III repository:
https://github.com/NMRLipids/NmrLipidsCholXray/blob/master/scratch/FFactor/FFstructCALC.sh
https://github.com/NMRLipids/NmrLipidsCholXray/tree/master/scratch/FFactor

However, I have not been able to install the SIMtoEXP program (http://link.springer.com/article/10.1007%2Fs00232-010-9254-5) so I have not been able to check my script against the standard method.

This  should be straighforward issue and should become clear once I check the details. Anyway, any kind of information from full exaplanation with citations to the hints of relevant literature are helpful here.

**Comment by GeorgPabst** [comment]
I am sending you SIMtoEXP...you might need a windows PC tough

**Comment by ohsOllila** [comment]
I am using Linux. The problem is in libraries, should be fixable. I will do it as soon as I have time. Any hints are welcomed. I have heard other people having similar problems with no solution yet.

**Comment by GeorgPabst** [comment]
I have heard from a new version of the program some time ago, which should be platform independent. Maybe Norbert knows more. I will write to him.

**Comment by ohsOllila** [comment]
This is now discussed in the [publication](http://dx.doi.org/10.1016/j.bbamem.2016.01.019). I have been now able to install SIMtoEXP and working on this in [NMRlipids III](https://github.com/NMRLipids/NmrLipidsCholXray).
